name: pyntcloud
channels:
  - conda-forge
dependencies:
- conda-forge::blas=1.1=openblas
- conda-forge::ca-certificates=2017.1.23=1
- conda-forge::certifi=2017.4.17=py36_0
- conda-forge::cycler=0.10.0=py36_0
- conda-forge::dbus=1.10.10=3
- conda-forge::decorator=4.0.11=py36_0
- conda-forge::expat=2.1.0=2
- conda-forge::fontconfig=2.12.1=4
- conda-forge::freetype=2.7=1
- conda-forge::gettext=0.19.7=1
- conda-forge::glib=2.51.4=0
- conda-forge::gst-plugins-base=1.8.0=0
- conda-forge::gstreamer=1.8.0=1
- conda-forge::icu=58.1=1
- conda-forge::ipykernel=4.6.1=py36_0
- conda-forge::ipython=6.0.0=py36_0
- conda-forge::ipython_genutils=0.2.0=py36_0
- conda-forge::jedi=0.10.0=py36_0
- conda-forge::jpeg=9b=0
- conda-forge::jupyter_client=5.0.1=py36_0
- conda-forge::jupyter_core=4.3.0=py36_0
- conda-forge::libffi=3.2.1=3
- conda-forge::libiconv=1.14=4
- conda-forge::libpng=1.6.28=0
- conda-forge::libsodium=1.0.10=0
- conda-forge::libxcb=1.12=1
- conda-forge::libxml2=2.9.4=4
- conda-forge::matplotlib=2.0.0=np112py36_3
- conda-forge::ncurses=5.9=10
- conda-forge::numpy=1.12.1=py36_blas_openblas_200
- conda-forge::openblas=0.2.19=2
- conda-forge::openssl=1.0.2k=0
- conda-forge::pandas=0.19.2=np112py36_1
- conda-forge::pcre=8.39=0
- conda-forge::pexpect=4.2.1=py36_0
- conda-forge::pickleshare=0.7.3=py36_0
- conda-forge::pip=9.0.1=py36_0
- conda-forge::prompt_toolkit=1.0.14=py36_0
- conda-forge::ptyprocess=0.5.1=py36_0
- conda-forge::py=1.4.33=py36_0
- conda-forge::pygments=2.2.0=py36_0
- conda-forge::pyparsing=2.2.0=py36_0
- conda-forge::pyqt=5.6.0=py36_2
- conda-forge::pytest=3.0.7=py36_0
- conda-forge::python=3.6.1=0
- conda-forge::python-dateutil=2.6.0=py36_0
- conda-forge::pytz=2017.2=py36_0
- conda-forge::pyzmq=16.0.2=py36_1
- conda-forge::qt=5.6.2=2
- conda-forge::readline=6.2=0
- conda-forge::scikit-learn=0.18.1=np112py36_blas_openblas_200
- conda-forge::scipy=0.19.0=np112py36_blas_openblas_200
- conda-forge::setuptools=33.1.1=py36_0
- conda-forge::simplegeneric=0.8.1=py36_0
- conda-forge::sip=4.18=py36_1
- conda-forge::six=1.10.0=py36_1
- conda-forge::sqlite=3.13.0=1
- conda-forge::tk=8.5.19=1
- conda-forge::tornado=4.5.1=py36_0
- conda-forge::traitlets=4.3.2=py36_0
- conda-forge::wcwidth=0.1.7=py36_0
- conda-forge::wheel=0.29.0=py36_0
- conda-forge::xorg-libxau=1.0.8=3
- conda-forge::xorg-libxdmcp=1.1.2=3
- conda-forge::xz=5.2.2=0
- conda-forge::zeromq=4.2.1=1
- conda-forge::zlib=1.2.11=0
- libgfortran=3.0.0=1
- llvmlite=0.17.0=py36_0
- numba=0.32.0=np112py36_0
- pip:
  - git+https://github.com/daavoo/pyntcloud.git
